///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SculptMyDream
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SculptMyDreamRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("15206195-e214-4677-88dd-61c6d1125866")]
    public partial class SculptMyDreamRepository : RepoGenBaseFolder
    {
        static SculptMyDreamRepository instance = new SculptMyDreamRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SculptMyDreamRepository element repository.
        /// </summary>
        [RepositoryFolder("15206195-e214-4677-88dd-61c6d1125866")]
        public static SculptMyDreamRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SculptMyDreamRepository() 
            : base("SculptMyDreamRepository", "/", null, 0, false, "15206195-e214-4677-88dd-61c6d1125866", ".\\RepositoryImages\\SculptMyDreamRepository15206195.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("15206195-e214-4677-88dd-61c6d1125866")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class SculptMyDreamRepositoryFolders
    {
    }
#pragma warning restore 0436
}